Bump maven-plugin-annotations from 3.6.4 to 3.7.0 (#572)
Bumps
[maven-plugin-annotations](https://github.com/apache/maven-plugin-tools)
from 3.6.4 to 3.7.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/apache/maven-plugin-tools/releases">maven-plugin-annotations's
releases</a>.</em></p>
<blockquote>
<h2>3.7.0</h2>
<h2>Bug</h2>
<ul>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-298">MPLUGIN-298</a>]
- The plugin descriptor generated by plugin:descriptor does not consider
@ see javadoc taglets</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-394">MPLUGIN-394</a>]
- Report-Mojo doesn't respect input encoding</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-403">MPLUGIN-403</a>]
- Generating site reports for plugin results in NoSuchMethodError</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-404">MPLUGIN-404</a>]
- JDK Requirements in plugin-info.html: Consider property
&quot;maven.compiler.release&quot;</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-420">MPLUGIN-420</a>]
- Parameters documentation inheriting @ since from Mojo can be
confusing</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-428">MPLUGIN-428</a>]
- Don't emit warning for missing javadoc URL of primitives</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-429">MPLUGIN-429</a>]
- Don't emit warning for missing javadoc URI if no javadoc sources are
configured</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-438">MPLUGIN-438</a>]
- Parameter description should be taken from annotated item</li>
</ul>
<h2>New Feature</h2>
<ul>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-9">MPLUGIN-9</a>] -
Add link to javadoc in configuration description page for user defined
types of Mojos.</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-396">MPLUGIN-396</a>]
- Allow only @ Deprecated annotation without @ deprecated javadoc
tag</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-400">MPLUGIN-400</a>]
- add system requirements history section</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-402">MPLUGIN-402</a>]
- report: allow to generate usage section in plugin-info.html with <!--
raw HTML omitted -->true<!-- raw HTML omitted --></li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-419">MPLUGIN-419</a>]
- Allow @ Parameter on setters methods</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-423">MPLUGIN-423</a>]
- Extract plugin report into its own plugin</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-427">MPLUGIN-427</a>]
- report: Expose generics information of Collection and Map types</li>
</ul>
<h2>Improvement</h2>
<ul>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-297">MPLUGIN-297</a>]
- plugin-info.html should contain a better Usage section</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-390">MPLUGIN-390</a>]
- Do not overwrite generate files with no content change</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-393">MPLUGIN-393</a>]
- Upgrade to JUnit 5 and @ Inject annotations</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-398">MPLUGIN-398</a>]
- Support for java 20 - ASM 9.4</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-405">MPLUGIN-405</a>]
- Don't print empty Memory, Disk Space in System Requirements</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-408">MPLUGIN-408</a>]
- simplification in helpmojo build</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-411">MPLUGIN-411</a>]
- Get rid of plexus-compiler-manager from tests</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-412">MPLUGIN-412</a>]
- Use Maven core artifacts in provided scope</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-417">MPLUGIN-417</a>]
- report and descriptor goal need to evaluate Javadoc comments
differently</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-433">MPLUGIN-433</a>]
- Allow to reference aggregator javadoc from plugin report</li>
</ul>
<h2>Task</h2>
<ul>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-378">MPLUGIN-378</a>]
- Detect legacy/javadoc Mojo definitions, warn to use Java 5
annotations</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-389">MPLUGIN-389</a>]
- Update level to Java 8</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-391">MPLUGIN-391</a>]
- Deprecate scripting support for mojos</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-406">MPLUGIN-406</a>]
- Deprecate requirements parameter in report Mojo</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-407">MPLUGIN-407</a>]
- Remove duplicate code from PluginReport</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-409">MPLUGIN-409</a>]
- Prepare for Doxia (Sitetools) 2.0.0</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-430">MPLUGIN-430</a>]
- Fix documentation for maven-plugin-report-plugin</li>
<li>[<a
href="https://issues.apache.org/jira/browse/MPLUGIN-431">MPLUGIN-431</a>]
- Remove deprecated items from new maven-plugin-report-plugin</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/apache/maven-plugin-tools/commit/0f2c0d563f45294e7005acd6f31aebbf9e99d3d5"><code>0f2c0d5</code></a>
[maven-release-plugin] prepare release maven-plugin-tools-3.7.0</li>
<li><a
href="https://github.com/apache/maven-plugin-tools/commit/76d99af45f275f3adf085d4d6ae4cca37c085782"><code>76d99af</code></a>
[MPLUGIN-438] Parameter description should be taken from annotated
item</li>
<li><a
href="https://github.com/apache/maven-plugin-tools/commit/5b6049090fefc8590c1aa9beeb34ac1a2e279e98"><code>5b60490</code></a>
[MPLUGIN-435] Revert MPLUGIN-410. Drop <a
href="https://github.com/Parameter"><code>@​Parameter</code></a>.implementation
and keep it ...</li>
<li><a
href="https://github.com/apache/maven-plugin-tools/commit/ebdb063ea287a208dd1553a6a21e362a33c14847"><code>ebdb063</code></a>
[MPLUGIN-437] Fixes to the plugin descriptor generation (<a
href="https://github-redirect.dependabot.com/apache/maven-plugin-tools/issues/167">#167</a>)</li>
<li><a
href="https://github.com/apache/maven-plugin-tools/commit/339fc29d84de0a5cd96ca5d77d0d52d9b6536157"><code>339fc29</code></a>
[MPLUGIN-433] Allow to disable link validation (<a
href="https://github-redirect.dependabot.com/apache/maven-plugin-tools/issues/162">#162</a>)</li>
<li><a
href="https://github.com/apache/maven-plugin-tools/commit/a191579a34d9f8a1e2d9a91b814428ad4bf4d853"><code>a191579</code></a>
[MPLUGIN-422] Upgrade to plexus-utils 3.5.0 (<a
href="https://github-redirect.dependabot.com/apache/maven-plugin-tools/issues/164">#164</a>)</li>
<li><a
href="https://github.com/apache/maven-plugin-tools/commit/664c16e2692a79e069e816dca44f9789839927a9"><code>664c16e</code></a>
[MPLUGIN-431] Remove deprecated items from new
maven-plugin-report-plugin</li>
<li><a
href="https://github.com/apache/maven-plugin-tools/commit/8a7640051ab2a4487e841fea6e21b95ac2d05ffe"><code>8a76400</code></a>
[MPLUGIN-427] only emit simple parameter type for configuration (<a
href="https://github-redirect.dependabot.com/apache/maven-plugin-tools/issues/163">#163</a>)</li>
<li><a
href="https://github.com/apache/maven-plugin-tools/commit/322a9bbb36d86598dff30f4b4b74eda8cd90259c"><code>322a9bb</code></a>
[MPLUGIN-434] Improve dependency management</li>
<li><a
href="https://github.com/apache/maven-plugin-tools/commit/a0ec0ba3f27804ec849344adaa96a9277628724a"><code>a0ec0ba</code></a>
[MPLUGIN-427] Expose generics information of parameter types in report
(<a
href="https://github-redirect.dependabot.com/apache/maven-plugin-tools/issues/159">#159</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/apache/maven-plugin-tools/compare/maven-plugin-tools-3.6.4...maven-plugin-tools-3.7.0">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.apache.maven.plugin-tools:maven-plugin-annotations&package-manager=gradle&previous-version=3.6.4&new-version=3.7.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>