Add agent to bridge JFR Streaming into metrics  (#115)
* Initial commit

* Add to main build

* Send data as deltas, get it into a sample backend (New Relic)

* Debug build issue

* Fix constants

* Package rename

* Initial commit

* Add to main build

* Send data as deltas, get it into a sample backend (New Relic)

* Debug build issue

* Fix constants

* Package rename

* Initial commit

* Add to main build

* Send data as deltas, get it into a sample backend (New Relic)

* Debug build issue

* Fix constants

* Package rename

* Initial commit

* Send data as deltas, get it into a sample backend (New Relic)

* Debug build issue

* Fix constants

* Package rename

* Get testcontainers imports set correctly

* BROKE: Prepare for rebase

* Finish migrating to 1.7.0

* BROKE: Test failing with NoSuchMethodError

* BROKE Tidy up docs

* FAIL: Pushing so other folks can have a look

* Unit tests are green

* Initial commit

* Add to main build

* Send data as deltas, get it into a sample backend (New Relic)

* Debug build issue

* Fix constants

* Package rename

* Initial commit

* Send data as deltas, get it into a sample backend (New Relic)

* Debug build issue

* Fix constants

* Package rename

* Get testcontainers imports set correctly

* BROKE: Prepare for rebase

* Initial commit

* Add to main build

* Send data as deltas, get it into a sample backend (New Relic)

* Debug build issue

* Fix constants

* Package rename

* Initial commit

* Send data as deltas, get it into a sample backend (New Relic)

* Debug build issue

* Fix constants

* Package rename

* Finish migrating to 1.7.0

* BROKE: Test failing with NoSuchMethodError

* BROKE Tidy up docs

* FAIL: Pushing so other folks can have a look

* Unit tests are green

* Fix broken build.gradle.kts

* Update jfr-streaming/build.gradle.kts

Co-authored-by: Anuraag Agrawal <anuraaga@gmail.com>

* BROKE: Versions

* Fix Javadoc task to version 17 as well

* Remove un-needed version

* Fix AttributeKey

* Work around Spotless not supporting type patterns yet

* Spotless Apply finaly works

* Real javaagent

* Provide programmatic endpoint, don't require test to depend on shadowJar

* Temporarily remove agent to land this faster

* Package rearrage

* Update jfr-streaming/build.gradle.kts

Co-authored-by: Anuraag Agrawal <anuraaga@gmail.com>

* Update jfr-streaming/build.gradle.kts

Co-authored-by: Anuraag Agrawal <anuraaga@gmail.com>

* Update jfr-streaming/build.gradle.kts

Co-authored-by: Anuraag Agrawal <anuraaga@gmail.com>

* Encapsulate more constants

* Minor tidyups

* Update jfr-streaming/build.gradle.kts

Co-authored-by: Anuraag Agrawal <anuraaga@gmail.com>

* Remove shadow Jar

* Remove unnecessary dependencies from build

* Change names and tidy up

* Basic Javadoc

* Fix descriptions

Co-authored-by: Anuraag Agrawal <anuraaga@gmail.com>